"""healthcare data and discharge ingestion

Revision ID: 10c82d1fbab4
Revises: 2a0000000001
"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "10c82d1fbab4"
down_revision: Union[str, None] = "2a0000000001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hospital_configurations",
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column("timezone", sa.String(length=100), nullable=False),
        sa.Column("calling_window_start", sa.Time(), nullable=False),
        sa.Column("calling_window_end", sa.Time(), nullable=False),
        sa.Column("default_follow_up_hours", sa.Integer(), nullable=False),
        sa.Column("max_concurrent_calls", sa.Integer(), nullable=False),
        sa.Column("default_max_retries", sa.Integer(), nullable=False),
        sa.Column("retry_initial_delay_minutes", sa.Integer(), nullable=False),
        sa.Column("retry_backoff_multiplier", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column(
            "notification_preferences", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("escalation_contacts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ehr_settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_ready", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "calling_window_end > calling_window_start",
            name=op.f("ck_hospital_configurations_calling_window"),
        ),
        sa.CheckConstraint(
            "default_follow_up_hours > 0", name=op.f("ck_hospital_configurations_follow_up_hours")
        ),
        sa.CheckConstraint(
            "default_max_retries >= 0", name=op.f("ck_hospital_configurations_max_retries")
        ),
        sa.CheckConstraint(
            "max_concurrent_calls > 0", name=op.f("ck_hospital_configurations_concurrent_calls")
        ),
        sa.CheckConstraint(
            "retry_backoff_multiplier >= 1", name=op.f("ck_hospital_configurations_retry_backoff")
        ),
        sa.CheckConstraint(
            "retry_initial_delay_minutes > 0", name=op.f("ck_hospital_configurations_retry_delay")
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_hospital_configurations_hospital_id_hospitals"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hospital_configurations")),
        sa.UniqueConstraint("hospital_id", name=op.f("uq_hospital_configurations_hospital_id")),
    )
    op.create_index(
        op.f("ix_hospital_configurations_hospital_id"),
        "hospital_configurations",
        ["hospital_id"],
        unique=False,
    )
    op.execute(
        """
        INSERT INTO hospital_configurations (
            id, hospital_id, timezone, calling_window_start, calling_window_end,
            default_follow_up_hours, max_concurrent_calls, default_max_retries,
            retry_initial_delay_minutes, retry_backoff_multiplier,
            notification_preferences, escalation_contacts, ehr_settings, is_ready
        )
        SELECT gen_random_uuid(), id, timezone, '09:00', '17:00', 72, 10, 3, 60, 2.0,
               '{}'::jsonb, '[]'::jsonb, '{}'::jsonb, false
        FROM hospitals
        """
    )
    op.create_table(
        "audit_events",
        sa.Column("actor_user_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("resource_type", sa.String(length=100), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"], ["users.id"], name=op.f("fk_audit_events_actor_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id"], ["hospitals.id"], name=op.f("fk_audit_events_hospital_id_hospitals")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(op.f("ix_audit_events_action"), "audit_events", ["action"], unique=False)
    op.create_index(
        op.f("ix_audit_events_actor_user_id"), "audit_events", ["actor_user_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_hospital_id"), "audit_events", ["hospital_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_occurred_at"), "audit_events", ["occurred_at"], unique=False
    )
    op.create_table(
        "discharge_imports",
        sa.Column("source", sa.String(length=255), nullable=False),
        sa.Column("source_digest", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("total_records", sa.Integer(), nullable=False),
        sa.Column("successful_records", sa.Integer(), nullable=False),
        sa.Column("failed_records", sa.Integer(), nullable=False),
        sa.Column("errors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'PARTIALLY_COMPLETED', 'FAILED')",
            name=op.f("ck_discharge_imports_status"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_discharge_imports_created_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_discharge_imports_hospital_id_hospitals"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_discharge_imports")),
        sa.UniqueConstraint(
            "hospital_id",
            "source_digest",
            name=op.f("uq_discharge_imports_hospital_id_source_digest"),
        ),
    )
    op.create_index(
        op.f("ix_discharge_imports_created_by_user_id"),
        "discharge_imports",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_discharge_imports_hospital_id"), "discharge_imports", ["hospital_id"], unique=False
    )
    op.create_index(
        op.f("ix_discharge_imports_status"), "discharge_imports", ["status"], unique=False
    )
    op.create_table(
        "care_plans",
        sa.Column("title", sa.String(length=250), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("follow_up_instructions", sa.Text(), nullable=False),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("encounter_id", sa.Uuid(), nullable=True),
        sa.Column("external_id", sa.String(length=150), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id", "patient_id", "encounter_id"],
            ["encounters.hospital_id", "encounters.patient_id", "encounters.id"],
            name=op.f("fk_care_plans_hospital_id_encounters"),
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id", "patient_id"],
            ["patients.hospital_id", "patients.id"],
            name=op.f("fk_care_plans_hospital_id_patients"),
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id"], ["hospitals.id"], name=op.f("fk_care_plans_hospital_id_hospitals")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_care_plans")),
        sa.UniqueConstraint(
            "hospital_id", "external_id", name=op.f("uq_care_plans_hospital_id_external_id")
        ),
    )
    op.create_index(
        op.f("ix_care_plans_encounter_id"), "care_plans", ["encounter_id"], unique=False
    )
    op.create_index(op.f("ix_care_plans_hospital_id"), "care_plans", ["hospital_id"], unique=False)
    op.create_index(op.f("ix_care_plans_patient_id"), "care_plans", ["patient_id"], unique=False)
    op.create_table(
        "conditions",
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=250), nullable=False),
        sa.Column("clinical_status", sa.String(length=30), nullable=False),
        sa.Column("onset_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("encounter_id", sa.Uuid(), nullable=True),
        sa.Column("external_id", sa.String(length=150), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id", "patient_id", "encounter_id"],
            ["encounters.hospital_id", "encounters.patient_id", "encounters.id"],
            name=op.f("fk_conditions_hospital_id_encounters"),
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id", "patient_id"],
            ["patients.hospital_id", "patients.id"],
            name=op.f("fk_conditions_hospital_id_patients"),
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id"], ["hospitals.id"], name=op.f("fk_conditions_hospital_id_hospitals")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conditions")),
        sa.UniqueConstraint(
            "hospital_id", "external_id", name=op.f("uq_conditions_hospital_id_external_id")
        ),
    )
    op.create_index(
        op.f("ix_conditions_encounter_id"), "conditions", ["encounter_id"], unique=False
    )
    op.create_index(op.f("ix_conditions_hospital_id"), "conditions", ["hospital_id"], unique=False)
    op.create_index(op.f("ix_conditions_patient_id"), "conditions", ["patient_id"], unique=False)
    op.create_table(
        "medications",
        sa.Column("medication_name", sa.String(length=250), nullable=False),
        sa.Column("medication_code", sa.String(length=100), nullable=True),
        sa.Column("dose", sa.String(length=100), nullable=True),
        sa.Column("route", sa.String(length=100), nullable=True),
        sa.Column("frequency", sa.String(length=100), nullable=True),
        sa.Column("instructions", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("encounter_id", sa.Uuid(), nullable=True),
        sa.Column("external_id", sa.String(length=150), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id", "patient_id", "encounter_id"],
            ["encounters.hospital_id", "encounters.patient_id", "encounters.id"],
            name=op.f("fk_medications_hospital_id_encounters"),
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id", "patient_id"],
            ["patients.hospital_id", "patients.id"],
            name=op.f("fk_medications_hospital_id_patients"),
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id"], ["hospitals.id"], name=op.f("fk_medications_hospital_id_hospitals")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_medications")),
        sa.UniqueConstraint(
            "hospital_id", "external_id", name=op.f("uq_medications_hospital_id_external_id")
        ),
    )
    op.create_index(
        op.f("ix_medications_encounter_id"), "medications", ["encounter_id"], unique=False
    )
    op.create_index(
        op.f("ix_medications_hospital_id"), "medications", ["hospital_id"], unique=False
    )
    op.create_index(op.f("ix_medications_patient_id"), "medications", ["patient_id"], unique=False)
    op.create_table(
        "observations",
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=250), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("unit", sa.String(length=50), nullable=True),
        sa.Column("value_type", sa.String(length=30), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("encounter_id", sa.Uuid(), nullable=True),
        sa.Column("external_id", sa.String(length=150), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id", "patient_id", "encounter_id"],
            ["encounters.hospital_id", "encounters.patient_id", "encounters.id"],
            name=op.f("fk_observations_hospital_id_encounters"),
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id", "patient_id"],
            ["patients.hospital_id", "patients.id"],
            name=op.f("fk_observations_hospital_id_patients"),
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id"], ["hospitals.id"], name=op.f("fk_observations_hospital_id_hospitals")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_observations")),
        sa.UniqueConstraint(
            "hospital_id", "external_id", name=op.f("uq_observations_hospital_id_external_id")
        ),
    )
    op.create_index(
        op.f("ix_observations_encounter_id"), "observations", ["encounter_id"], unique=False
    )
    op.create_index(
        op.f("ix_observations_hospital_id"), "observations", ["hospital_id"], unique=False
    )
    op.create_index(
        op.f("ix_observations_observed_at"), "observations", ["observed_at"], unique=False
    )
    op.create_index(
        op.f("ix_observations_patient_id"), "observations", ["patient_id"], unique=False
    )
    op.create_table(
        "procedures",
        sa.Column("code", sa.String(length=100), nullable=True),
        sa.Column("name", sa.String(length=250), nullable=False),
        sa.Column("performed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("encounter_id", sa.Uuid(), nullable=True),
        sa.Column("external_id", sa.String(length=150), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id", "patient_id", "encounter_id"],
            ["encounters.hospital_id", "encounters.patient_id", "encounters.id"],
            name=op.f("fk_procedures_hospital_id_encounters"),
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id", "patient_id"],
            ["patients.hospital_id", "patients.id"],
            name=op.f("fk_procedures_hospital_id_patients"),
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id"], ["hospitals.id"], name=op.f("fk_procedures_hospital_id_hospitals")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_procedures")),
        sa.UniqueConstraint(
            "hospital_id", "external_id", name=op.f("uq_procedures_hospital_id_external_id")
        ),
    )
    op.create_index(
        op.f("ix_procedures_encounter_id"), "procedures", ["encounter_id"], unique=False
    )
    op.create_index(op.f("ix_procedures_hospital_id"), "procedures", ["hospital_id"], unique=False)
    op.create_index(op.f("ix_procedures_patient_id"), "procedures", ["patient_id"], unique=False)
    op.create_index(
        op.f("ix_procedures_performed_at"), "procedures", ["performed_at"], unique=False
    )
    op.add_column(
        "discharges",
        sa.Column("follow_up_window_hours", sa.Integer(), server_default="72", nullable=False),
    )
    op.add_column(
        "discharges",
        sa.Column("disposition", sa.String(length=50), server_default="HOME", nullable=False),
    )
    op.add_column(
        "discharges",
        sa.Column(
            "risk_indicators",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "discharges",
        sa.Column("communication_eligible", sa.Boolean(), server_default=sa.true(), nullable=False),
    )
    op.add_column("discharges", sa.Column("source_reference", sa.String(length=200), nullable=True))
    op.add_column(
        "discharges",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "discharges",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_discharges_discharge_at"), "discharges", ["discharge_at"], unique=False
    )
    op.create_index(
        op.f("ix_discharges_follow_up_deadline"), "discharges", ["follow_up_deadline"], unique=False
    )
    op.create_index(op.f("ix_discharges_risk_level"), "discharges", ["risk_level"], unique=False)
    op.create_unique_constraint(
        op.f("uq_discharges_hospital_id_source_reference"),
        "discharges",
        ["hospital_id", "source_reference"],
    )
    op.add_column(
        "encounters",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "encounters",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("encounters", "updated_at")
    op.drop_column("encounters", "created_at")
    op.drop_constraint(
        op.f("uq_discharges_hospital_id_source_reference"), "discharges", type_="unique"
    )
    op.drop_index(op.f("ix_discharges_risk_level"), table_name="discharges")
    op.drop_index(op.f("ix_discharges_follow_up_deadline"), table_name="discharges")
    op.drop_index(op.f("ix_discharges_discharge_at"), table_name="discharges")
    op.drop_column("discharges", "updated_at")
    op.drop_column("discharges", "created_at")
    op.drop_column("discharges", "source_reference")
    op.drop_column("discharges", "communication_eligible")
    op.drop_column("discharges", "risk_indicators")
    op.drop_column("discharges", "disposition")
    op.drop_column("discharges", "follow_up_window_hours")
    op.drop_index(op.f("ix_procedures_performed_at"), table_name="procedures")
    op.drop_index(op.f("ix_procedures_patient_id"), table_name="procedures")
    op.drop_index(op.f("ix_procedures_hospital_id"), table_name="procedures")
    op.drop_index(op.f("ix_procedures_encounter_id"), table_name="procedures")
    op.drop_table("procedures")
    op.drop_index(op.f("ix_observations_patient_id"), table_name="observations")
    op.drop_index(op.f("ix_observations_observed_at"), table_name="observations")
    op.drop_index(op.f("ix_observations_hospital_id"), table_name="observations")
    op.drop_index(op.f("ix_observations_encounter_id"), table_name="observations")
    op.drop_table("observations")
    op.drop_index(op.f("ix_medications_patient_id"), table_name="medications")
    op.drop_index(op.f("ix_medications_hospital_id"), table_name="medications")
    op.drop_index(op.f("ix_medications_encounter_id"), table_name="medications")
    op.drop_table("medications")
    op.drop_index(op.f("ix_conditions_patient_id"), table_name="conditions")
    op.drop_index(op.f("ix_conditions_hospital_id"), table_name="conditions")
    op.drop_index(op.f("ix_conditions_encounter_id"), table_name="conditions")
    op.drop_table("conditions")
    op.drop_index(op.f("ix_care_plans_patient_id"), table_name="care_plans")
    op.drop_index(op.f("ix_care_plans_hospital_id"), table_name="care_plans")
    op.drop_index(op.f("ix_care_plans_encounter_id"), table_name="care_plans")
    op.drop_table("care_plans")
    op.drop_index(op.f("ix_discharge_imports_status"), table_name="discharge_imports")
    op.drop_index(op.f("ix_discharge_imports_hospital_id"), table_name="discharge_imports")
    op.drop_index(op.f("ix_discharge_imports_created_by_user_id"), table_name="discharge_imports")
    op.drop_table("discharge_imports")
    op.drop_index(op.f("ix_audit_events_occurred_at"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_hospital_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_actor_user_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_action"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(
        op.f("ix_hospital_configurations_hospital_id"), table_name="hospital_configurations"
    )
    op.drop_table("hospital_configurations")
    # ### end Alembic commands ###
